
stages:
  - test
  - build
  - prod

install_env_test:
  stage: test
  script:
    - echo "intall envairman"

tets_env:
  stage: test
  script:
    - echo "check env"

build_stage:
  stage: build
  script:
    - ping google.com -c 2


prod_depoyment:
  stage: prod
  script:
    - ./prod.sh
  when: manual


